question_data_db = [
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Sports",
        "question": "There are a total of 20 races in the Formula One 2016 season.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "type": "boolean",
        "difficulty": "hard",
        "category": "Science & Nature",
        "question": "The chemical element Lithium is named after the country of Lithuania.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Science: Mathematics",
        "question": "The 'Squaring the Circle' problem is solvable.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "type": "boolean",
        "difficulty": "medium",
        "category": "General Knowledge",
        "question": "A pencil's lead is typically made from graphite, not lead.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "General Knowledge",
        "question": "Scotland voted to become an independent country during the referendum in September 2014.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Entertainment: Video Games",
        "question": 'In "Sonic Adventure", you are able to transform into Super Sonic at will after completing the main story.',
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "type": "boolean",
        "difficulty": "hard",
        "category": "Science: Mathematics",
        "question": 'The binary number "101001101" is equivalent to the decimal number "334".',
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "History",
        "question": "The United States Department of Homeland Security was formed in response to the September 11th attacks.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "General Knowledge",
        "question": "When you cry in space, your tears stick to your face.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Entertainment: Board Games",
        "question": "The top human players can easily beat the top computers at chess.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "type": "boolean",
        "difficulty": "medium",
        "category": "Science: Computers",
        "question": "The first computer bug was caused by faulty wires.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "type": "boolean",
        "difficulty": "medium",
        "category": "Science: Computers",
        "question": "Linus Sebastian is the creator of the Linux kernel, which is used in Linux, Android, and Chrome OS.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Entertainment: Video Games",
        "question": 'In the "S.T.A.L.K.E.R." series, the Freedom faction wishes to destroy the supernatural area known as "the Zone".',
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "type": "boolean",
        "difficulty": "medium",
        "category": "Vehicles",
        "question": "Ferrari has never made a V10 engine for any of its cars.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "type": "boolean",
        "difficulty": "medium",
        "category": "Entertainment: Video Games",
        "question": 'In the game "Subnautica", a "Cave Crawler" will attack you.',
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
]
